*** Variables ***
#Test Data
${name}=    User1
${email}=    user1@gmail.com
${phone}=    9022504565
${address}=    Indexnine Technologies\\nPune, 411041
${country_one}=    India
${country_two}=    Canada
${color_1}=    White
${color_2}=    Blue
${color_3}=    Yellow
${animal_1}=    Zebra
${animal_2}=    Lion
${animal_3}=    Cat
${date1}=    01/21/2026
${date2}=    12/02/2026
${date3}=    18/02/2026
${single_file}=    C:\\Users\\Kirti.Deng\\Pictures\\Screenshots\\Screenshot 2026-01-08 180145.png
${single_file1}=    C:\\Users\\Kirti.Deng\\Pictures\\Screenshots\\Screenshot 2026-01-08 164523.png
${multiple_files}=    ${single_file}\n${single_file1}